# Generated by Django 6.1 on 2026-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=100)),
                ('customer_issue', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('agent_performance', models.TextField(blank=True)),
                ('key_topics', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
